@url = http://localhost:3000/api

###
GET {{url}}/posts
Content-Type: application/json

###
GET {{url}}/authors
Content-Type: application/json


###
POST {{url}}/authors
Content-Type: application/json

{
    "name": "Dani",
    "email": "dani@example.com",
    "image": "https://dani.com/imagen.jpg"
}

###
GET {{url}}/authors/5/posts
Content-Type: application/json

###
POST {{url}}/posts
Content-Type: application/json

{
    "title": "prueba finalisima",
    "description": "esto es una prueba",
    "category": "pruebas",
    "authors_id": 18
}
